---
- name: Login to dockerHub
  docker_login:
    username: manelbaabou
    password: dockerhubmanel123
    reauthorize: yes
- name: Tag and push to docker hub
  docker_image:
    name: devops
    repository: manelbaabou/devops
    tag: latest
    push: yes
    source: local
