---
# tasks file for prometheus
- name: Run prometheus container 
  shell: docker run -d -p 9090:9090 -v /home/amine/Continious_Delivery/ansible/roles/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus 
